---
# tasks file for k3s installation
- name: Download and install k3s
  shell: curl -sfL https://k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s service is started and enabled
  systemd:
    name: k3s
    state: started
    enabled: yes
---

